# Site settings
title: Brilliantly wrong
email: alex.rogozhnikov@yandex.ru
description: Brilliantly Wrong - Alex Rogozhnikov's blog about math, machine learning, prgramming and high energy physics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arogozhnikov.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  arogozhnikov
# Build settings
markdown: kramdown
